language: node_js
sudo: true
node_js:
  - '8'
cache:
  directories:
    - node_modules
jobs:
  include:
    - stage: test
      if: (branch = master) AND (NOT (type IN (pull_request)))
      script:
        - yarn install
        - yarn test
        - yarn build
