export const aliOSS = '//yancey-assets.oss-cn-beijing.aliyuncs.com';
export const webpSuffix = '?x-oss-process=image/format,webp';
export const thumbSuffix = '?x-oss-process=image/resize,w_120/quality,Q_10';

export const svgSprite = {
  telegram: '#telegram',
  github: '#github',
  soundcloud: '#soundcloud',
  paypal: '#paypal',
  rocket1: '#rocket',
  megaphone: '#megaphone',
  more: '#more',
  sandClock: '#sand-clock',
  heart: '#heart',
  rocket2: '#startup',
  instagram: '#instagram',
  fire: '#flame',
  wechat: '#wechat',
  twitter1: '#twitter',
  barcelona: '#barcelona',
  fireworks: '#fireworks',
  eye: '#eye',
  apple: '#apple',
  ubuntu: '#ubuntu',
  new: '#new',
  cv: '#curriculum-vitae',
  tools: '#gear',
  mail: '#mail',
  comments1: '#multimedia',
  code1: '#html-coding',
  openFolder: '#open-folder',
  archive: '#archive-black-box',
  home: '#home',
  share1: '#share-symbol',
  rss: '#rss-symbol',
  appStore: '#app-store-apple-symbol',
  blog: '#blogger-letter-logotype',
  comments2: '#blog-comment-speech-bubble-symbol',
  search1: '#musica-searcher',
  photo: '#frame-landscape',
  settings: '#settings',
  camera: '#photo-camera',
  rightArrow: '#right-arrow',
  leftArrow: '#left-arrow',
  link: '#unlink',
  user: '#user',
  share2: '#share',
  like: '#like',
  time: '#time',
  closeFolder: '#folder',
  music: '#music-player',
  leftQuote: '#left-quote',
  rightQuote: '#right-quote',
  search2: '#magnifying-glass',
  history: '#history',
  mortarBoard: '#mortarboard',
  code2: '#code',
  crown: '#placeholder',
  tag: '#price-tag',
  balloons: '#balloons',
  twitter2: '#twitter-1',
  planet: '#twitter-1',
  astronaut: '#astronaut',
  close: '#close',
}

export const socialMediaList = {
  github: {
    url: 'https://github.com/YanceyOfficial',
    icon: svgSprite.github,
  },
  twitter: {
    url: 'https://www.twitter.com/YanceyOfficial',
    icon: svgSprite.twitter1,
  },
  facebook: {
    url: 'https://www.facebook.com/yanceyleo',
    icon: svgSprite.close,
  },
  instagram: {
    url: 'https://www.instagram.com/yancey_leo',
    icon: svgSprite.instagram,
  },
}

export const mail = 'team@yanceyleo.com';